//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecoverUnsoldAdmin.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class App_fr {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal App_fr() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("RecoverUnsoldAdmin.Resources.App_fr", typeof(App_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        internal static string Customers {
            get {
                return ResourceManager.GetString("Customers", resourceCulture);
            }
        }
        
        internal static string Distributors {
            get {
                return ResourceManager.GetString("Distributors", resourceCulture);
            }
        }
        
        internal static string Offers {
            get {
                return ResourceManager.GetString("Offers", resourceCulture);
            }
        }
        
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        internal static string SelectLanguage {
            get {
                return ResourceManager.GetString("SelectLanguage", resourceCulture);
            }
        }
        
        internal static string Orders {
            get {
                return ResourceManager.GetString("Orders", resourceCulture);
            }
        }
        
        internal static string FinalizedOrders {
            get {
                return ResourceManager.GetString("FinalizedOrders", resourceCulture);
            }
        }
        
        internal static string TotalSales {
            get {
                return ResourceManager.GetString("TotalSales", resourceCulture);
            }
        }
        
        internal static string OfferPublishedPerDay {
            get {
                return ResourceManager.GetString("OfferPublishedPerDay", resourceCulture);
            }
        }
        
        internal static string OrdersPerDay {
            get {
                return ResourceManager.GetString("OrdersPerDay", resourceCulture);
            }
        }
        
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        internal static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        internal static string RegistrationDate {
            get {
                return ResourceManager.GetString("RegistrationDate", resourceCulture);
            }
        }
        
        internal static string AccountVerificationDate {
            get {
                return ResourceManager.GetString("AccountVerificationDate", resourceCulture);
            }
        }
        
        internal static string NoCustomerFound {
            get {
                return ResourceManager.GetString("NoCustomerFound", resourceCulture);
            }
        }
        
        internal static string DarkTheme {
            get {
                return ResourceManager.GetString("DarkTheme", resourceCulture);
            }
        }
        
        internal static string LightTheme {
            get {
                return ResourceManager.GetString("LightTheme", resourceCulture);
            }
        }
        
        internal static string NoDistributorsFound {
            get {
                return ResourceManager.GetString("NoDistributorsFound", resourceCulture);
            }
        }
        
        internal static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        internal static string TaxId {
            get {
                return ResourceManager.GetString("TaxId", resourceCulture);
            }
        }
        
        internal static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        internal static string DetailsForDistributor {
            get {
                return ResourceManager.GetString("DetailsForDistributor", resourceCulture);
            }
        }
        
        internal static string AccountNotVerified {
            get {
                return ResourceManager.GetString("AccountNotVerified", resourceCulture);
            }
        }
        
        internal static string AccountVerifiedThe {
            get {
                return ResourceManager.GetString("AccountVerifiedThe", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Indication {
            get {
                return ResourceManager.GetString("Indication", resourceCulture);
            }
        }
        
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        internal static string Rccm {
            get {
                return ResourceManager.GetString("Rccm", resourceCulture);
            }
        }
        
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        internal static string RowsPerPage {
            get {
                return ResourceManager.GetString("RowsPerPage", resourceCulture);
            }
        }
        
        internal static string MinDate {
            get {
                return ResourceManager.GetString("MinDate", resourceCulture);
            }
        }
        
        internal static string MaxDate {
            get {
                return ResourceManager.GetString("MaxDate", resourceCulture);
            }
        }
        
        internal static string MinPrice {
            get {
                return ResourceManager.GetString("MinPrice", resourceCulture);
            }
        }
        
        internal static string MaxPrice {
            get {
                return ResourceManager.GetString("MaxPrice", resourceCulture);
            }
        }
        
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        internal static string Beneficiaries {
            get {
                return ResourceManager.GetString("Beneficiaries", resourceCulture);
            }
        }
        
        internal static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        internal static string Distributor {
            get {
                return ResourceManager.GetString("Distributor", resourceCulture);
            }
        }
        
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        internal static string NoOfferFound {
            get {
                return ResourceManager.GetString("NoOfferFound", resourceCulture);
            }
        }
        
        internal static string PageInfo {
            get {
                return ResourceManager.GetString("PageInfo", resourceCulture);
            }
        }
        
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        internal static string OfferDetails {
            get {
                return ResourceManager.GetString("OfferDetails", resourceCulture);
            }
        }
        
        internal static string TotalAmount {
            get {
                return ResourceManager.GetString("TotalAmount", resourceCulture);
            }
        }
        
        internal static string OfferNotFound {
            get {
                return ResourceManager.GetString("OfferNotFound", resourceCulture);
            }
        }
        
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        internal static string Products {
            get {
                return ResourceManager.GetString("Products", resourceCulture);
            }
        }
        
        internal static string NoProductsFound {
            get {
                return ResourceManager.GetString("NoProductsFound", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        internal static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string LogoutSuccessful {
            get {
                return ResourceManager.GetString("LogoutSuccessful", resourceCulture);
            }
        }
        
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        internal static string AccountUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountUpdatedSuccessfully", resourceCulture);
            }
        }
        
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string OnlinePayment {
            get {
                return ResourceManager.GetString("OnlinePayment", resourceCulture);
            }
        }
        
        internal static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        internal static string NoReportsFound {
            get {
                return ResourceManager.GetString("NoReportsFound", resourceCulture);
            }
        }
        
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        internal static string ReportedDistributor {
            get {
                return ResourceManager.GetString("ReportedDistributor", resourceCulture);
            }
        }
        
        internal static string Reason {
            get {
                return ResourceManager.GetString("Reason", resourceCulture);
            }
        }
        
        internal static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        internal static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        internal static string Processed {
            get {
                return ResourceManager.GetString("Processed", resourceCulture);
            }
        }
        
        internal static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        internal static string SuspendDistributorAccount {
            get {
                return ResourceManager.GetString("SuspendDistributorAccount", resourceCulture);
            }
        }
        
        internal static string ReportProcessedSuccessfully {
            get {
                return ResourceManager.GetString("ReportProcessedSuccessfully", resourceCulture);
            }
        }
        
        internal static string MarkAsProcessed {
            get {
                return ResourceManager.GetString("MarkAsProcessed", resourceCulture);
            }
        }
        
        internal static string MarkAsUnprocessed {
            get {
                return ResourceManager.GetString("MarkAsUnprocessed", resourceCulture);
            }
        }
        
        internal static string SuspendDistributor {
            get {
                return ResourceManager.GetString("SuspendDistributor", resourceCulture);
            }
        }
        
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        internal static string DistributorAccountSuspendedSuccessfully {
            get {
                return ResourceManager.GetString("DistributorAccountSuspendedSuccessfully", resourceCulture);
            }
        }
        
        internal static string ReceivedReports {
            get {
                return ResourceManager.GetString("ReceivedReports", resourceCulture);
            }
        }
        
        internal static string AccountSuspensionRevokedSuccessfully {
            get {
                return ResourceManager.GetString("AccountSuspensionRevokedSuccessfully", resourceCulture);
            }
        }
        
        internal static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        internal static string AccountSuspensions {
            get {
                return ResourceManager.GetString("AccountSuspensions", resourceCulture);
            }
        }
        
        internal static string Cancelled {
            get {
                return ResourceManager.GetString("Cancelled", resourceCulture);
            }
        }
    }
}
